
package workspace;

import java.util.HashMap;
import java.util.Map;
import javax.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import us.kbase.common.service.Tuple12;
import us.kbase.common.service.UObject;


/**
 * <p>Original spec-file type: get_object_output</p>
 * <pre>
 * Output generated by the "get_object" function. Provided for backwards
 * compatibility.
 *         
 * UnspecifiedObject data - The object's data.
 * object_metadata metadata - Metadata for object retrieved/
 *         
 * @deprecated Workspaces.ObjectData
 * </pre>
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@Generated("com.googlecode.jsonschema2pojo")
@JsonPropertyOrder({
    "data",
    "metadata"
})
public class GetObjectOutput {

    @JsonProperty("data")
    private UObject data;
    @JsonProperty("metadata")
    private Tuple12 <String, String, String, Long, String, String, String, String, String, String, Map<String, String> , Long> metadata;
    private Map<java.lang.String, Object> additionalProperties = new HashMap<java.lang.String, Object>();

    @JsonProperty("data")
    public UObject getData() {
        return data;
    }

    @JsonProperty("data")
    public void setData(UObject data) {
        this.data = data;
    }

    public GetObjectOutput withData(UObject data) {
        this.data = data;
        return this;
    }

    @JsonProperty("metadata")
    public Tuple12 <String, String, String, Long, String, String, String, String, String, String, Map<String, String> , Long> getMetadata() {
        return metadata;
    }

    @JsonProperty("metadata")
    public void setMetadata(Tuple12 <String, String, String, Long, String, String, String, String, String, String, Map<String, String> , Long> metadata) {
        this.metadata = metadata;
    }

    public GetObjectOutput withMetadata(Tuple12 <String, String, String, Long, String, String, String, String, String, String, Map<String, String> , Long> metadata) {
        this.metadata = metadata;
        return this;
    }

    @JsonAnyGetter
    public Map<java.lang.String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperties(java.lang.String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public java.lang.String toString() {
        return ((((((("GetObjectOutput"+" [data=")+ data)+", metadata=")+ metadata)+", additionalProperties=")+ additionalProperties)+"]");
    }

}
